btcpayserver/BTCPayServer.Lightning

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.CLightning/JsonConverters/ShortChannelIdJsonConverter.cs
src/BTCPayServer.Lightning.CLightning/ListChannelsResponse.cs
src/BTCPayServer.Lightning.CLightning/PeerInfo.cs
src/BTCPayServer.Lightning.CLightning/ShortChannelId.cs
src/BTCPayServer.Lightning.Charge/ChargeClient.cs
src/BTCPayServer.Lightning.Common/ILightningClient.cs
src/BTCPayServer.Lightning.Common/LightningChannel.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
tests/CommonTests.cs

I want this for my project. And I suppose the function is generic enough to be implemented in `ILightningClient` .

Add `ILightningClient.ListChannels`

---

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs

Ping @joemphilips can you review this?

Improve code on ListChannel of c-lightning

---

src/BTCPayServer.Lightning.All/LightningClientFactory.cs
src/BTCPayServer.Lightning.All/LightningConnectionString.cs
src/BTCPayServer.Lightning.Ptarmigan/PtarmiganClient.cs
src/BTCPayServer.Lightning.Ptarmigan/PtarmiganLightningClient.cs
src/BTCPayServer.Lightning.Ptarmigan/PtarmiganSession.cs
tests/CommonTests.cs
tests/Tester.cs
tests/docker-compose.yml

We rebuilt Ptarmigan’s `invoice notifications(WebSocket)` and made the API compatible with BTCPayServer.Lightning.
https://github.com/btcpayserver/BTCPayServer.Lightning/pull/14#issuecomment-504451618

Rebuilt Ptarmigan's invoice notifications

---

src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.Eclair/Models/ChannelResponse.cs
src/BTCPayServer.Lightning.Eclair/Models/GetSentInfoResponse.cs
src/BTCPayServer.Lightning.Eclair/Models/PaymentStatus.cs
tests/docker-compose.yml

Update to the latest eclair API

Update eclair integration

---

src/BTCPayServer.Lightning.All/ConnectChannels.cs
src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.Charge/ChargeClient.cs
src/BTCPayServer.Lightning.Common/CreateInvoiceParams.cs
src/BTCPayServer.Lightning.Common/ILightningClient.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
src/BTCPayServer.Lightning.Ptarmigan/PtarmiganLightningClient.cs

Needed in order to close: https://github.com/btcpayserver/btcpayserver/issues/1480
I've also snuck in commit that advances blocks in case of pending channels - this should deal with the test problems we have in BtcPayServer.Tests when we update LND versions.

Adding support for private route hints

---

src/BTCPayServer.Lightning.All/LightningClientFactory.cs
src/BTCPayServer.Lightning.All/LightningConnectionString.cs
src/BTCPayServer.Lightning.Charge/ChargeClient.cs

Allow insecure for Charge

---

tests/docker-compose.yml

Works on my machine, let's see if it works for y'all as well.

Bumping LND to 0.13.1-beta

---

tests/docker-compose.yml

Updating to newest release: https://github.com/lightningnetwork/lnd/releases/tag/v0.14.2-beta

Bumping LND to 0.14.2-beta

---

src/BTCPayServer.Lightning.LNbank/LNbankClient.cs
src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs
src/BTCPayServer.Lightning.LNbank/Models/CreateInvoiceRequest.cs

Prerequisite for btcpayserver/btcpayserver#3423.

LNbank: Add private route hints field for create invoice request

---

.circleci/config.yml

Fixes the `unknown flag: --v` error.

Update docker-compose command

---

src/BTCPayServer.Lightning.All/ConnectChannels.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.Eclair/Models/ChannelResponse.cs
src/BTCPayServer.Lightning.Eclair/Models/PayInvoiceRequest.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
tests/CommonTests.cs

Multiple fixes for the tests as well as the payment and list channel methods in LND and Eclair. Those got surfaced by the recent flakyness in the tests.

Fixes and improvements

---

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.CLightning/CLightningPayment.cs
src/BTCPayServer.Lightning.Charge/ChargeClient.cs
src/BTCPayServer.Lightning.Common/ILightningClient.cs
src/BTCPayServer.Lightning.Common/JsonConverters/LightMoneyJsonConverter.cs
src/BTCPayServer.Lightning.Common/LightningInvoice.cs
src/BTCPayServer.Lightning.Common/LightningInvoiceStatus.cs
src/BTCPayServer.Lightning.Common/LightningPayment.cs
src/BTCPayServer.Lightning.Common/LightningPaymentStatus.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.LND/Base64Url.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
src/BTCPayServer.Lightning.LND/LndSwaggerClient.cs
src/BTCPayServer.Lightning.LNbank/LNbankClient.cs
src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs
src/BTCPayServer.Lightning.LNbank/Models/PaymentData.cs
tests/CommonTests.cs

This adds the `GetPayment` method, which allows to retrieve the payment info by payment hash.

Add GetPayment method

---

src/BTCPayServer.Lightning.LNbank/LNbankClient.cs
src/BTCPayServer.Lightning.LNbank/Models/CreateInvoiceRequest.cs

Fixes btcpayserver/btcpayserver-plugins#20

Add description hash to LNbank CreateInvoiceRequest

---

src/BTCPayServer.Lightning.LND/LndClient.cs

The [trackpayment endpoint](https://api.lightning.community/?shell#v2-router-track) offers only streaming responses, this updates takes care of that.
I've used the existing `LndInvoiceClientSession` as a template for implementing this.

LND: Handle streaming trackpayment response correctly

---

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.Common/PayInvoiceParams.cs
src/BTCPayServer.Lightning.Eclair/EclairClient.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.Eclair/Models/PayInvoiceRequest.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
src/BTCPayServer.Lightning.LND/LndSwaggerClient.cs
tests/CommonTests.cs

Various smaller LND fixes/updates as well as the ability to allow and handle zero amount invoices.
Prerequisites for
- btcpayserver/btcpayserver-plugins#23
- btcpayserver/btcpayserver-plugins#25

Allow and handle zero amount invoices & LND updates

---

src/BTCPayServer.Lightning.All/ConnectChannels.cs
src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.Charge/ChargeClient.cs
src/BTCPayServer.Lightning.Common/BOLT11PaymentRequest.cs
src/BTCPayServer.Lightning.Eclair/EclairClient.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
tests/CommonTests.cs
tests/JsonTests.cs
tests/Logs.cs
tests/Tester.cs

Some minor improvements and fixes I came across while working on something different :)

Various updates

---

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.Charge/ChargeClient.cs
src/BTCPayServer.Lightning.Charge/ChargeSession.cs
src/BTCPayServer.Lightning.Common/ILightningClient.cs
src/BTCPayServer.Lightning.Common/WebsocketHelper.cs
src/BTCPayServer.Lightning.Common/WebsocketListener.cs
src/BTCPayServer.Lightning.Eclair/EclairClient.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
src/BTCPayServer.Lightning.LND/LndSwaggerClient.cs
src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs
tests/CommonTests.cs

Add and pass missing cancellation tokens

---

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.CLightning/GetInfoResponse.cs
src/BTCPayServer.Lightning.CLightning/ListFundsResponse.cs
src/BTCPayServer.Lightning.Charge/ChargeClient.cs
src/BTCPayServer.Lightning.Common/ILightningClient.cs
src/BTCPayServer.Lightning.Common/JsonConverters/LightMoneyJsonConverter.cs
src/BTCPayServer.Lightning.Common/LightningNodeBalance.cs
src/BTCPayServer.Lightning.Eclair/EclairClient.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.Eclair/Models/GlobalBalanceResponse.cs
src/BTCPayServer.Lightning.Eclair/Models/UsableBalance.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
src/BTCPayServer.Lightning.LND/LndSwaggerClient.cs
src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs
tests/CommonTests.cs

Implementations and tests for Core Lightning, LND and Eclair.
Closes #73.

Add GetBalance

---

src/BTCPayServer.Lightning.LND/LndSwaggerClient.cs

This commit adds support for the force-close argument in LND's CloseChannel API.

LND: support channel force-close

---

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.CLightning/ListFundsResponse.cs
src/BTCPayServer.Lightning.Common/LightningNodeBalance.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.Eclair/Models/GlobalBalanceResponse.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
tests/CommonTests.cs
tests/Tester.cs

Followup of https://github.com/btcpayserver/BTCPayServer.Lightning/pull/85

OnChain balances should show sats

---

tests/Tester.cs
tests/docker-compose.yml

They got disabled in e136aaa169365130a10fd86bd912764e6439d251.

Bring back LNDhub tests

---

tests/docker-compose.yml

Updating to newest release: https://github.com/lightningnetwork/lnd/releases/tag/v0.15.0-beta

Bumping LND to 0.15.0-beta

---

src/BTCPayServer.Lightning.LNDhub/JsonConverters/LndHubBufferJsonConverter.cs
src/BTCPayServer.Lightning.LNDhub/JsonConverters/LndHubDateTimeOffsetConverter.cs
src/BTCPayServer.Lightning.LNDhub/JsonConverters/LndHubLightMoneyJsonConverter.cs
src/BTCPayServer.Lightning.LNDhub/JsonConverters/LndHubTimeSpanJsonConverter.cs
src/BTCPayServer.Lightning.LNDhub/LndHubClient.cs
src/BTCPayServer.Lightning.LNDhub/LndHubLightningClient.cs
src/BTCPayServer.Lightning.LNDhub/LndHubUtil.cs
src/BTCPayServer.Lightning.LNDhub/Models/BalanceData.cs
src/BTCPayServer.Lightning.LNDhub/Models/CreateInvoiceRequest.cs
src/BTCPayServer.Lightning.LNDhub/Models/DecodeInvoiceData.cs
src/BTCPayServer.Lightning.LNDhub/Models/InvoiceData.cs
src/BTCPayServer.Lightning.LNDhub/Models/NodeInfoData.cs
src/BTCPayServer.Lightning.LNDhub/Models/PayInvoiceRequest.cs
src/BTCPayServer.Lightning.LNDhub/Models/PaymentData.cs
src/BTCPayServer.Lightning.LNDhub/Models/TransactionData.cs
tests/CommonTests.cs

Refactor models and JSON converters to make them reusable. I've made these changes based on the LNbank + LNDhub API compatibility (see dennisreimann/btcpayserver#19).

LNDhub refactoring

---

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs

We simply weren't using it. Might help fixing btcpayserver/btcpayserver#4070.

Core Lightning: Incorporate private route hints parameter

---

src/BTCPayServer.Lightning.All/LightningClientFactory.cs
src/BTCPayServer.Lightning.All/LightningConnectionString.cs
src/BTCPayServer.Lightning.Eclair/EclairClient.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs

Support username for eclair connection

---

tests/docker-compose.yml

Updating to newest release: https://github.com/lightningnetwork/lnd/releases/tag/v0.15.2-beta

Bumping LND to 0.15.2-beta

---

src/BTCPayServer.Lightning.Common/BTCPayServer.Lightning.Common.csproj
src/BTCPayServer.Lightning.LNbank/LNbankClient.cs
src/BTCPayServer.Lightning.LNbank/Models/CreateInvoiceRequest.cs

Fixes btcpayserver/btcpayserver#4496

LNbank: Add missing DescriptionHashOnly parameter

---

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.Charge/ChargeClient.cs
src/BTCPayServer.Lightning.Common/ILightningClient.cs
src/BTCPayServer.Lightning.Common/PayResponse.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
src/BTCPayServer.Lightning.LND/LndSwaggerClient.cs
src/BTCPayServer.Lightning.LNDhub/LndHubLightningClient.cs
src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs
tests/CommonTests.cs

Extracted from #111:
- Add GetInvoice by payment hash
- PayResponse: Add payment hash, preimage and status to payment details

Payment hash

---

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
src/BTCPayServer.Lightning.CLightning/CLightningInvoice.cs
src/BTCPayServer.Lightning.Common/LightningInvoice.cs
src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
src/BTCPayServer.Lightning.LND/LndClient.cs
src/BTCPayServer.Lightning.LNDhub/LndHubLightningClient.cs
src/BTCPayServer.Lightning.LNDhub/LndHubUtil.cs
src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs
src/BTCPayServer.Lightning.LNbank/Models/InvoiceData.cs
tests/CommonTests.cs

Prerequisite for btcpayserver/btcpayserver#4475.

Add payment hash and preimage to LightningInvoice

---

src/BTCPayServer.Lightning.LNDhub/LndHubLightningClient.cs

Details in btcpayserver/btcpayserver#5083

LNDhub: Improve GetInfo method

---

tests/docker-compose.yml

See btcpayserver/btcpayserver-docker#828.

Update LND image version

---

src/BTCPayServer.Lightning.Phoenixd/PhoenixdLightningClient.cs

Fix issue from https://github.com/btcpayserver/btcpayserver/issues/6779

Fix chain to be more generic
