btcpayserver/BTCPayServer.Lightning

src/BTCPayServer.Lightning.LND/LndClient.cs
To avoid null reference exception when there were no channels.
I have tested this manually in local.
=> return empty array when there were no channels in LndClient.ListChannels

src/BTCPayServer.Lightning.LND/LndClient.cs
I'm so sorry for sending small PR so often. :( There was one more case that SwaggerClient returns null for its value
=> check null value for active

src/BTCPayServer.Lightning.Common/LightMoney.cs, tests/CommonTests.cs
It has been multiplying the value twice
1. in public static constructors (e.g `LightMoney.Satoshis` ) 
2. in the default constructor (i.e. `LightMoney(decimal amount LightMoneyUnit unit)` )
which will result to much larger value than a user expects.
=> Fix bug in static constructor in LightMoney

src/BTCPayServer.Lightning.Common/BOLT11PaymentRequest.cs
The TryParse method seemed wrongly implemented, where it didnt return a bool indicating success/failure and still threw an exception on failure
=> fix bolt11 TryParse

tests/Tester.cs, tests/docker-compose.yml
This PR enable bitcoind `txindex` during test as it's required by Eclair implementation and re-enable eclair's test. I would also like to update the eclair version used in the test to the newly released 0.3.3 but we're currently experiencing some issues with the dockerhub integration, i'll update this PR if the new image becomes available.
Fixes #26
=> Restore eclair test

src/BTCPayServer.Lightning.Common/BOLT11PaymentRequest.cs
LND 0.12 will start rejecting payments that don't include address by default. Any developer using our Lightning library will need `uint256 PaymentSecret` expose to comply with this requirement.
More details on: 
https://github.com/lightningnetwork/lnd/pull/4752
=> Adding support for PaymentSecret in BOLT11 parser

tests/CommonTests.cs, tests/Tester.cs, tests/docker-compose.yml
I've built a custom Docker image `btcpayserver/lnd:v0.11.x-beta-notls` by adding our scripts on top of @halseth branch, see last 2 commits here:
https://github.com/btcpayserver/lnd/commits/option-no-tls
In this PR you can see how I'm setting `hostname` and then utilizing it through lnd.conf variables. It seems to be working as expected.
You can see that all tests are passing - if things look good on your machine I guess you can merge. 
I've tried it in `btcpayserver` and it also works, the only tricky thing is that it seems 0.0.0.0 rest listener was working on both HTTP and HTTPS. I've needed to modify some variables in order to make things work (introduced `LND_REST_LISTEN_HOST` for wallet auto-init script)... but no other obvious side effect.
=> Switching to using container built from non-forked codebase

src/BTCPayServer.Lightning.Common/BOLT11PaymentRequest.cs, src/BTCPayServer.Lightning.Common/FeatureBits.cs, tests/CommonTests.cs
This PR adds support for Destination Feature bits in the Bolt11 parser. The parsed feature bits are stored as integer corresponding to their position in the feature bits (see https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#feature-bits).
For better documentation an enum for the numerous Bolt11 fields is created.
In addition to adding a unit test case for the feature bits also the payment address is now checked as that was not done before.
=> Adding support for DestFeatures in Bolt11 parser

BTCPayServer.Lightning.sln, README.md, src/BTCPayServer.Lightning.All/BTCPayServer.Lightning.All.csproj, src/BTCPayServer.Lightning.All/LightningClientFactory.cs, src/BTCPayServer.Lightning.All/LightningConnectionString.cs, src/BTCPayServer.Lightning.Common/ConnectionResult.cs, src/BTCPayServer.Lightning.Common/OpenChannelResponse.cs, src/BTCPayServer.Lightning.LNbank/BTCPayServer.Lightning.LNbank.csproj, src/BTCPayServer.Lightning.LNbank/LNbankClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankHubClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs, src/BTCPayServer.Lightning.LNbank/Models/ChannelData.cs, src/BTCPayServer.Lightning.LNbank/Models/ConnectNodeRequest.cs, src/BTCPayServer.Lightning.LNbank/Models/CreateChannelRequest.cs, src/BTCPayServer.Lightning.LNbank/Models/CreateInvoiceRequest.cs, src/BTCPayServer.Lightning.LNbank/Models/ErrorData.cs, src/BTCPayServer.Lightning.LNbank/Models/InvoiceData.cs, src/BTCPayServer.Lightning.LNbank/Models/NodeInfoData.cs, src/BTCPayServer.Lightning.LNbank/Models/PayInvoiceRequest.cs, src/BTCPayServer.Lightning.LNbank/Models/TransactionUpdateEvent.cs, src/BTCPayServer.Lightning.LNbank/PushNuget.ps1, src/PushNuget.ps1, tests/CommonTests.cs
Adds the LNbank client, so that LNbank wallets can be used as a Lightning node/backend in BTCPay Server. 
See [details on the integration](https://github.com/dennisreimann/btcpayserver-lnbank#btcpay-server-integration).
=> Add LNbank client

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs, src/BTCPayServer.Lightning.CLightning/CLightningPayResponse.cs, src/BTCPayServer.Lightning.Common/PayResponse.cs, src/BTCPayServer.Lightning.Eclair/EclairClient.cs, src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs, src/BTCPayServer.Lightning.Eclair/Models/GetSentInfoRequest.cs, src/BTCPayServer.Lightning.Eclair/Models/GetSentInfoResponse.cs, src/BTCPayServer.Lightning.LND/LndClient.cs, src/BTCPayServer.Lightning.LND/LndSwaggerClient.cs, tests/CommonTests.cs
Adds `PayDetails` to the `PayResponse`, consisting of the total amount paid and the fees.
Added for c-lightning, LND and Eclair. Works for LNbank too, because it just passes the response through.
=> Add payment details

src/BTCPayServer.Lightning.Common/BOLT11PaymentRequest.cs, tests/CommonTests.cs
Currently the `DescriptionHash` field of a Bolt11 invoice is read as little-endian, but is actually encoded as [big-endian](https://github.com/lightning/bolts/blob/master/11-payment-encoding.md#tagged-fields) (See also how the `PaymentHash` and `PaymentSecret` fields are treated). 
I have also added a test reading the description hash value from a Bolt11 invoice.
=> Read DescriptionHash field as big-endian

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs, src/BTCPayServer.Lightning.Charge/ChargeClient.cs, src/BTCPayServer.Lightning.Common/ILightningClient.cs, src/BTCPayServer.Lightning.Common/PayInvoiceParams.cs, src/BTCPayServer.Lightning.Eclair/EclairClient.cs, src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs, src/BTCPayServer.Lightning.Eclair/Models/PayInvoiceRequest.cs, src/BTCPayServer.Lightning.LND/LndClient.cs, src/BTCPayServer.Lightning.LND/LndSwaggerClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs, src/BTCPayServer.Lightning.LNbank/Models/PayInvoiceRequest.cs, tests/CommonTests.cs
Adds `MaxFeePercent` to the `PayInvoiceRequest`, an optional/nullable float property expressing the fee limit as a percentage of the payment amount.
Added for all `ILightningClient` implementations (not supported by Charge though)
=> Add optional max fee percentage when paying

src/BTCPayServer.Lightning.LNbank/LNbankClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankHubClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs
This fixes the transaction hub URL. 
Can you merge and do a new release, @NicolasDorier? I'll then update the Lightning lib in BTCPay and create a new LNbank version.
=> LNbank: Fix transaction hub URL

.circleci/config.yml
As in btcpayserver/btcpayserver#3475: CircleCI recently [deprecated build images](https://circleci.com/blog/ubuntu-14-16-image-deprecation/), including the classic ones we are using.
=> Update CircleCI build

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
The property is only set when the status is "complete". [Details](https://lightning.readthedocs.io/lightning-listpays.7.html)
=> C-Lightning: Null-check payment preimage

src/BTCPayServer.Lightning.Common/LightningNodeBalance.cs, src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs, src/BTCPayServer.Lightning.LND/LndClient.cs, src/BTCPayServer.Lightning.LNDhub/LndHubLightningClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs, tests/CommonTests.cs
- Do not respond with zero amounts if data is not available - send null instead. This will allow for better interpretation on the client side.
- Adds support for checking the balance of a LNbank wallet.
=> Lightning balance: Update responses, support balance check in LNbank

src/BTCPayServer.Lightning.LND/LndClient.cs
The API returns sats, not millisats.
=> Fix LND onchain balance

README.md, src/BTCPayServer.Lightning.All/LightningConnectionString.cs, tests/CommonTests.cs
Fixes the missing LNDhub connection type in the `ToString` method and adds parsing for `lndhub://` URLs, so that we don't have to explain how to convert it to the connection string format.
Also adds that additional information to the README.
=> Connection string updates

README.md, src/BTCPayServer.Lightning.All/BTCPayServer.Lightning.All.csproj, src/BTCPayServer.Lightning.All/LightningClientFactory.cs, src/BTCPayServer.Lightning.All/LightningConnectionString.cs, src/BTCPayServer.Lightning.CLightning/BTCPayServer.Lightning.CLightning.csproj, src/BTCPayServer.Lightning.Charge/BTCPayServer.Lightning.Charge.csproj, src/BTCPayServer.Lightning.Common/BTCPayServer.Lightning.Common.csproj, src/BTCPayServer.Lightning.Eclair/BTCPayServer.Lightning.Eclair.csproj, src/BTCPayServer.Lightning.LND/BTCPayServer.Lightning.LND.csproj, src/BTCPayServer.Lightning.LND/LndRestSettings.cs, src/BTCPayServer.Lightning.LND/LndSwaggerClient.partial.cs, src/BTCPayServer.Lightning.LNDhub/BTCPayServer.Lightning.LNDhub.csproj, src/BTCPayServer.Lightning.LNbank/BTCPayServer.Lightning.LNbank.csproj, tests/BTCPayServer.Lightning.Tests.csproj, tests/Dockerfile
When the LND certificate expires or changes because of added hosts the
certthumbprint changes and is not updated automatically, forcing users
to update the configuration.  workaround is is to allow insecure
connections but that is obviously not secure.
This change adds a new configuration option `certfilepath` to set the
path of the certificate. The certificate located at that path is loaded
at each attempt to connect to LND and checked to contain server-supplied
certificate. If it's present the connection is accepted.
This is required for resolving
https://github.com/btcpayserver/btcpayserver/issues/2182
This raises required dotnet version, I guess it's OK since BTCPayServer raised it too.
=> Support certificate file path

src/BTCPayServer.Lightning.Common/BOLT11PaymentRequest.cs, src/BTCPayServer.Lightning.Common/FeatureBits.cs, tests/CommonTests.cs
The feature bits for  `PaymentMetadata` that have been formally accepted into the bolt specification would currently result in an overflow when parsing and hence set unrelated feature bits. This PR therefore changes the backing of the enum `FeatureBits` to Int64 to allow for more enums to be represented and adds this feature bits and a test case for it.
Additionally this PR adds the not yet formalized `AMPRequired` feature bits used by LND. Note that even without changing the backing to Int64 for the feature bits this does _not_ overflow, as that is the highest enum value representable currently. I hope it is in the interest of adding this feature bits in parsing invoices as those may be encountered in real-world already even though it is not formalized yet.
Note that a more future proof …
=> Increase feature bits space and add `AMPRequired` and `PaymentMetadata*` features bits

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs, tests/CommonTests.cs
Expiry unit needs to be [seconds](https://lightning.readthedocs.io/lightning-invoice.7.html), not milliseconds: "The expiry is optionally the time the invoice is valid for, in seconds."
=> Core Lightning: Fix and test expiry

src/BTCPayServer.Lightning.Common/LightningInvoice.cs, src/BTCPayServer.Lightning.Common/PayInvoiceParams.cs, src/BTCPayServer.Lightning.LND/LndClient.cs, tests/CommonTests.cs
Builds on the keysend feature added in #96.
Custom [TLV records](https://github.com/satoshisstream/satoshis.stream/blob/main/TLV_registry.md) only work for LND right now, Core Lightning support might come, see ElementsProject/lightning#4470
=> Add custom TLV records to invoice

src/BTCPayServer.Lightning.LNDhub/JsonConverters/LndHubLightMoneyJsonConverter.cs
Fixes the exception `System.OverflowException: Value was either too large or too small for an Int32.`
=> LNDhub: Fix JSON conversion

src/BTCPayServer.Lightning.All/BTCPayServer.Lightning.All.csproj, src/BTCPayServer.Lightning.CLightning/BTCPayServer.Lightning.CLightning.csproj, src/BTCPayServer.Lightning.CLightning/CLightningClient.cs, src/BTCPayServer.Lightning.Charge/BTCPayServer.Lightning.Charge.csproj, src/BTCPayServer.Lightning.Common/BTCPayServer.Lightning.Common.csproj, src/BTCPayServer.Lightning.Common/LightningPayment.cs, src/BTCPayServer.Lightning.Common/PayInvoiceParams.cs, src/BTCPayServer.Lightning.Common/PayResponse.cs, src/BTCPayServer.Lightning.Eclair/BTCPayServer.Lightning.Eclair.csproj, src/BTCPayServer.Lightning.LND/BTCPayServer.Lightning.LND.csproj, src/BTCPayServer.Lightning.LND/LndClient.cs, src/BTCPayServer.Lightning.LNDhub/BTCPayServer.Lightning.LNDhub.csproj, src/BTCPayServer.Lightning.LNbank/BTCPayServer.Lightning.LNbank.csproj
Times out invoice payments after 30 seconds and returns the new `PayResult.Unknown` in those cases.
Clients like the Greenfield API can then call/poll `GetPayment` to get the state and result for pending payments.
Here is what an in-flight payment response from the Greenfield API will look like — I can send a PR for the required changes once this PR is merged, because it required the added `PayResult.Unknown`:
For context see [this comment](https://github.com/btcpayserver/btcpayserver/issues/3781#issuecomment-1293446246).
=> LND/CLN: Timeout payments and respond gracefully

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.15.4-beta-1/images/sha256-cadbbff93cf36146e24fa4f32170b4b9d278a2e1acfdc50470790a94506ee9c3?context=explore
=> Bumping LND to 0.15.4-beta-1

src/BTCPayServer.Lightning.All/BTCPayServer.Lightning.All.csproj, src/BTCPayServer.Lightning.All/ConnectChannels.cs, src/BTCPayServer.Lightning.CLightning/BTCPayServer.Lightning.CLightning.csproj, src/BTCPayServer.Lightning.CLightning/CLightningClient.cs, src/BTCPayServer.Lightning.Charge/BTCPayServer.Lightning.Charge.csproj, src/BTCPayServer.Lightning.Charge/ChargeClient.cs, src/BTCPayServer.Lightning.Common/BTCPayServer.Lightning.Common.csproj, src/BTCPayServer.Lightning.Common/CreateInvoiceParams.cs, src/BTCPayServer.Lightning.Eclair/BTCPayServer.Lightning.Eclair.csproj, src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs, src/BTCPayServer.Lightning.LND/BTCPayServer.Lightning.LND.csproj, src/BTCPayServer.Lightning.LNDhub/BTCPayServer.Lightning.LNDhub.csproj, src/BTCPayServer.Lightning.LNbank/BTCPayServer.Lightning.LNbank.csproj, tests/CommonTests.cs, tests/docker-compose.yml
Before this PR, users of `CreateInvoiceParams` who wanted the `DescriptionHash` in the BOLT11 needed to pass the hash to `CreateInvoiceParams.DescriptionHash`.
The problem with this was that:
1. Core lightning require the `Description` to natively create BOLT11 invoices with description hash. It was not provided before by users.
2. Users need to care about the endianness and shoot themselves in the foot. (we actually did in the tests)
I refactored the `CLIghtningClient.CreateInvoice` to be smart enough to work on the native Core lightning 22.11 API, but also fallback on the `invoicewithdescriptionhash` plugin if that is not possible.
I manually tested that the client still worked on `0.10.2`, and also if we could activate `allow-deprecated-api=false` on c-lightning, in which case the …
=> Introduce CreateInvoiceParams.DescriptionHashOnly

src/BTCPayServer.Lightning.Eclair/EclairClient.cs, src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs, src/BTCPayServer.Lightning.Eclair/Models/GetSentInfoResponse.cs, src/BTCPayServer.Lightning.Eclair/Models/GlobalBalanceResponse.cs, src/BTCPayServer.Lightning.Eclair/Models/PaymentStatus.cs, src/BTCPayServer.Lightning.Eclair/Models/SendToNodeRequest.cs, tests/CommonTests.cs, tests/docker-compose.yml
Extracted these from #111:
- Incorporate payment timeout pattern from #106
- Improve failure response
- Fix missing payment info (some [`getsentinfo` properties](https://acinq.github.io/eclair/#getsentinfo) weren't correct)
- Upgrade containers to 0.8.0
=> Eclair updates

src/BTCPayServer.Lightning.Eclair/JsonConverters/EclairBtcJsonConverter.cs, src/BTCPayServer.Lightning.Eclair/Models/GlobalBalanceResponse.cs, tests/JsonTests.cs
Eclair denominates global balance amounts in BTC and Charge seems to export large amounts as floats.
The solution is to separate the two clearly and fix the float conversion in the `LightMoneyJsonConverter`.
Fixes btcpayserver/btcpayserver#4383.
=> LightMoney: Fix float conversion

src/BTCPayServer.Lightning.All/BTCPayServer.Lightning.All.csproj, src/BTCPayServer.Lightning.Common/CreateInvoiceParams.cs, src/BTCPayServer.Lightning.Common/JsonConverters/TimeSpanJsonConverter.cs, src/BTCPayServer.Lightning.LNbank/LNbankClient.cs, src/BTCPayServer.Lightning.LNbank/Models/CreateInvoiceRequest.cs
Fixes btcpayserver/btcpayserver#4458 by adding TimeSpan conversion for the request classes.
The Logging.Abstractions upgrade fixes version mismatches with BTCPay Server ­— I came across those when I integrated the Lightning lib locally inside the main project to debug this.
=> LNbank fixes

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs, src/BTCPayServer.Lightning.LND/LndClient.cs, tests/CommonTests.cs
Additions to #119:
- CLN: Allow fetching invoice by payment hash with string
- LND: Fix invoice response if there is no preimage
Came across these while working on btcpayserver/btcpayserver#4520.
=> Payment hash updates

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankHubClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs, src/BTCPayServer.Lightning.LNbank/Models/TransactionUpdateEvent.cs
Corrects a mistake in CLN I must have made where the Preimage property gets populated with the PaymentSecret as a fallback.
Makes the LNbank listener prefer the payment hash to lookup an invoice. Falls back to invoice id and makes it clearer, that both might be used.
=> CLN + LNbank: Minor updates

src/BTCPayServer.Lightning.LNDhub/JsonConverters/LndHubBufferJsonConverter.cs, src/BTCPayServer.Lightning.LNDhub/LndHubLightningClient.cs
Handles the case `r_hash` as a string. LNDhub sends it as a Buffer object, LNDhub.go as string. Closes btcpayserver/btcpayserver#4658.
=> LNDhub: Make InvoiceData compatible with LNDhub.go

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.16.0-beta/images/sha256-ddc2dea59306e45957ea9a4bdd8b0d39662bf1996f89b6bc193922a33b07951d?context=repo
=> Bumping LND to 0.16.0-beta

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.16.1-beta/images/sha256-8cd728f1103ae9994dbbdd0f10d12807a946706d91f885af1b2ba13737eb722e?context=explore
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.16.1-beta
=> Bumping LND to 0.16.1-beta

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.16.2-beta/images/sha256-ce3bf85e3380cd74d8e1ecdab6c0d45ad8364a4c3689be0de6cc23fca20d8c81?context=explore
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.16.2-beta
=> Bumping LND to 0.16.2-beta

src/BTCPayServer.Lightning.All/BTCPayServer.Lightning.All.csproj, src/BTCPayServer.Lightning.LNbank/BTCPayServer.Lightning.LNbank.csproj, src/BTCPayServer.Lightning.LNbank/LNbankHubClient.cs, src/BTCPayServer.Lightning.LNbank/LNbankLightningClient.cs
Fixes dennisreimann/btcpayserver-plugin-lnbank#33
Every times a new invoice come, a new handler would listen to the hub. Eventually, the client would stop seeing new lightning transactions.
Ping @dennisreimann
=> Fix LNBank listening loop

src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs
Minor fix for this build warning in the Eclair module:
```
/src/BTCPayServer.Lightning.Eclair/EclairLightningClient.cs(450,25): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. [/src/BTCPayServer.Lightning.Eclair/BTCPayServer.Lightning.Eclair.csproj]
```
=> Eclair: Fix build warning

src/BTCPayServer.Lightning.LND/LndClient.cs
At a later point we can expose the HTLCs completely, for now this is a simple fix for the aggregation of the custom records with multiple settled HTLCs.
=> LND: Fix custom record aggregation

src/BTCPayServer.Lightning.LND/LndClient.cs, src/BTCPayServer.Lightning.LND/LndSwaggerClient.cs
It seems that `litd` doesn't support `r_hash_str` because it's deprecated by LND.
If that's true, we should just switch, not only to support `litd`, but so next LND update doesn't break us.
Source: https://lightning.engineering/api-docs/api/lnd/lightning/lookup-invoice/index.html
=> Use r_hash instead of r_hash_str for LND

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.16.3-beta/images/sha256-9ff34769378cfca18664c7d1da3747e7ad7fb7f38a9a7b82a3d4f85e5bfef7bf?context=explore
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.16.3-beta
=> Bumping LND to 0.16.3-beta

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.16.4-beta/images/sha256-83667cf6efa57b903244847691dd99f01a64e8f6ba18f4b7506754886df7cecc?context=explore
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.16.4-beta
=> Bumping LND to 0.16.4-beta

src/BTCPayServer.Lightning.All/LightningConnectionString.cs
Before, if supportLegacy was true, it would not attempt to parse lndhub style connections
=> Fix order of parsing logic

src/BTCPayServer.Lightning.LNDhub/JsonConverters/LndHubLightMoneyJsonConverter.cs, tests/JsonTests.cs
From the [LNDhub docs](https://github.com/BlueWallet/LndHub/blob/master/doc/Send-requirements.md): "All amounts are satoshis (int)"
Fixes dennisreimann/btcpayserver-plugin-lndhub-api#3.
=> LNDhub: Convert LightMoney to int instead of decimal

src/BTCPayServer.Lightning.CLightning/CLightningClient.cs
From the CLN docs: 
> maxfee overrides both maxfeepercent and exemptfee defaults (and if you specify maxfee you cannot specify either of those), and creates an absolute limit on what fee we will pay. This allows you to implement your own heuristics rather than the primitive ones used here.
https://docs.corelightning.org/reference/lightning-pay
=> Explicitly set maxfee in CLN

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.17.0-beta/images/sha256-58b98f983cd786bcb4d48ea8586144cafd44d58dc3018e26bfbfcf875f495368?context=explore
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.17.0-beta
=> Bumping LND to 0.17.0-beta

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.17.1-beta/images/sha256-b5c106136bd33a422463c736a1db8bd3541f95ac6f277dae86ab2a01b0c3445a?context=explore
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.17.1-beta
=> Bumping LND to 0.17.1-beta

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.17.2-beta/images/sha256-936767369b703a67daf6db6a008a3b53c15f407d29a7ad2327a0de28f5951b30?context=explore
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.17.2-beta
=> Bumping LND to 0.17.2-beta

src/BTCPayServer.Lightning.LNDhub/JsonConverters/LndHubTimeSpanJsonConverter.cs, src/BTCPayServer.Lightning.LNDhub/LndHubClient.cs, src/BTCPayServer.Lightning.LNDhub/LndHubConnectionStringHandler.cs, src/BTCPayServer.Lightning.LNDhub/LndHubInvoiceListener.cs, src/BTCPayServer.Lightning.LNDhub/LndHubUtil.cs, src/BTCPayServer.Lightning.LNDhub/Models/PaymentResponse.cs, tests/CommonTests.cs
- Ensures trailing slash for base URI
- Handles `allowinsecure` for `lndhub://` scheme URLs
- Removes unused imports
Context: dennisreimann/btcpayserver-plugin-lnbank#51
=> LNDhub fixes

src/BTCPayServer.Lightning.LNDhub/AsyncDuplicateLock.cs, src/BTCPayServer.Lightning.LNDhub/LndHubClient.cs, src/BTCPayServer.Lightning.LNDhub/LndHubInvoiceListener.cs, src/BTCPayServer.Lightning.LNDhub/LndHubLightningClient.cs, src/BTCPayServer.Lightning.LNDhub/Models/AuthResponse.cs, tests/CommonTests.cs
This option is so popular that is was ddosing Alby. We had some severe exessive roundtrips. This PR:
* Caches the access token/refresh token in memory, and the expiry time is extracted from the access token.
* If the expiry is close (5mins), we use the refresh token to get a new access token
* If there are multiple clients using the same user (url and credentials), it reuses the access token instead of asking for a new one
* If there are multiple invoice watchers, only one will actively request invoices, while the others will read from cache. As soon as it is inactive, another switches to fetching the invoices.
=> Optimize LNDHub

README.md, src/BTCPayServer.Lightning.LND/LndClient.cs, src/BTCPayServer.Lightning.LND/LndError.cs
The goal of this is to allow usage with non-admin macaroons in BTCPay Server.
=> LND: Handle permission errors for GetInfo

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.17.3-beta/images/sha256-141611de6c062835e9513dd1ec4155c779d7a7b55258eb1fe06e228b0835fa56?context=repo
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.17.3-beta
=> Bumping LND to 0.17.3-beta

tests/BTCPayServer.Lightning.Tests.csproj, tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.17.4-beta-rc1/images/sha256-26f86b586d691680bfe56b796394bdd7e1900d1fb095947fbe5d3e22fb30d0bd?context=explore
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.17.4-beta-rc1
=> Bumping LND to 0.17.4-beta-rc1

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.17.4-beta/images/sha256-b62ecff5ca71d37f9b4846f35b4d86ddc4faa3fc1dd0618ae9221d99f47708bd?context=explore
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.17.4-beta
=> Bumping LND to 0.17.4-beta

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.18.0-beta/images/sha256-e6043dddf0bdbd5c740e882447c441b37f87f2c736ebb08747a4aff5e100d9bf?context=repo
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.18.0-beta
=> Bumping LND to 0.18.0-beta

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.18.1-beta/images/sha256-5fbfa76a218ab59bf9206485f4c0c071a525f9f0906255a5672054741d043b79?context=repo
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.18.1-beta
=> Bumping LND to 0.18.1-beta

.circleci/config.yml, tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.18.3-beta/images/sha256-e7449187b058440e4746f948bd095584d67bb82133c93737204e86c3aeff664a?context=repo
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.18.3-beta
=> Bumping LND to 0.18.3-beta

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/layers/btcpayserver/lnd/v0.18.4-beta/images/sha256-ead59bbc8c9ea3dc76fc4122b31c12bd3b5f86acd7416ac42c0c4fc010f2d25e
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.18.4-beta
=> Bumping LND to 0.18.4-beta

tests/docker-compose.yml
Updating to newest release: https://hub.docker.com/repository/docker/btcpayserver/lnd/tags/v0.18.5-beta/sha256-61ee37ef066024088531e4b26971590f1b7d131fc824fa3443cba70f782d0d30
Tag: https://github.com/btcpayserver/lnd/releases/tag/basedon-v0.18.5-beta
=> Bumping LND to 0.18.5-beta
